=== folio-org/mod-user-import/ramls/schemas/customField.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Custom Field",
  "description": "Custom field item schema",
  "javaType": "org.folio.rest.jaxrs.model.CustomField",
  "additionalProperties": false,
  "properties": {
    "id": {
      "description": "A UUID identifying this custom field",
      "$ref": "raml-util/schemas/uuid.schema",
      "example": "f973c3b6-85fc-4d35-bda8-f31b568957bf",
      "readonly": true,
      "excludedFromEqualsAndHashCode": true
    },
    "name": {
      "type": "string",
      "description": "The name of the custom field",
      "example": "Department"
    },
    "refId": {
      "type": "string",
      "description": "The reference id of the custom field. Read only, autogenerated field",
      "example": "department"
    },
    "type": {
      "type": "string",
      "description": "The type of the custom field",
      "$ref": "customFieldTypes.json",
      "example": "RADIO_BUTTON",
      "readonly": true
    },
    "entityType": {
      "type": "string",
      "description": "The entity type, the custom field is assigned to",
      "example": "package"
    },
    "visible": {
      "type": "boolean",
      "description": "Defines visibility of the custom field",
      "example": true
    },
    "required": {
      "type": "boolean",
      "description": "Defines if the custom field is required",
      "example": true
    },
    "isRepeatable": {
      "type": "boolean",
      "description": "Defines if the custom field is repeatable",
      "example": true
    },
    "order": {
      "type": "integer",
      "description": "The order of the custom field to be displayed",
      "example": 1,
      "readonly": true
    },
    "helpText": {
      "type": "string",
      "description": "The description of the custom field",
      "example": "Provide a department"
    },
    "checkboxField": {
      "type": "object",
      "description": "Checkbox field properties",
      "$ref": "checkboxField.json"
    },
    "selectField": {
      "type": "object",
      "description": "Select field properties",
      "$ref": "selectField.json"
    },
    "textField": {
      "type": "object",
      "description": "Text field properties",
      "$ref": "textField.json",
      "readonly": true
    },
    "displayInAccordion": {
      "type": "string",
      "description": "Display in accordion names for the custom field"
    },
    "metadata": {
      "description": "User metadata information",
      "$ref": "raml-util/schemas/metadata.schema",
      "readonly": true
    }
  },
  "required": [
    "refId"
  ]
}

=== folio-org/mod-user-import/src/test/resources/custom-fields.json
{
    "name" : "Class Year",
    "refId" : "classYear",
    "type" : "SINGLE_SELECT_DROPDOWN",
    "entityType" : "user",
    "visible" : true,
    "required" : false,
    "isRepeatable" : false,
    "order" : 1,
    "helpText" : "",
    "selectField" : {
        "multiSelect" : false,
        "options" : {
            "values" : [
                {
                    "id" : "opt_0",
                    "value" : "Employee",
                    "default" : false
                },
                {
                    "id" : "opt_1",
                    "value" : "Exchange Student",
                    "default" : false
                },
                {
                    "id" : "opt_2",
                    "value" : "Other",
                    "default" : false
                },
                {
                    "id" : "opt_3",
                    "value" : "Part Time",
                    "default" : false
                }
            ]
        }
    }
}
