=== folio-org/mod-user-import/ramls/schemas/userdataimportCollection.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "User Data Import Collection Schema",
  "description": "The user data import collection",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "users": {
      "id": "usersData",
      "type": "array",
      "description": "List of users' data to import",
      "items": {
        "type": "object",
        "$ref": "userdataimport.json"
      }
    },
    "totalRecords": {
      "description": "Total number of users' data to import",
      "type": "integer"
    },
    "deactivateMissingUsers": {
      "description": "Indicates whether to deactivate users that missing in current users' data collection",
      "type": "boolean"
    },
    "updateOnlyPresentFields": {
      "description": "Indicates whether to update only present fields in user's data. Currently this only works for addresses.",
      "type": "boolean"
    },
    "sourceType": {
      "description": "A prefix for the externalSystemId",
      "type": "string"
    },
    "included": {
      "description": "Entities that should be imported with users",
      "javaType": "org.folio.rest.jaxrs.model.IncludedObjects",
      "additionalProperties": false,
      "type": "object",
      "properties": {
        "departments": {
          "description": "Departments entities that should be imported with users",
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "object",
            "$ref": "department.json"
          }
        },
        "customFields": {
          "description": "Custom fields entities that should be updated with users",
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "object",
            "$ref": "customField.json"
          }
        }
      }
    }
  },
  "required": [
    "users",
    "totalRecords"
  ]
}

=== folio-org/mod-user-import/ramls/examples/userdataimportCollection.json
{
  "users": [
    {
      "username": "jhandey",
      "externalSystemId": "111_112",
      "barcode": "1234567",
      "active": true,
      "patronGroup": "staff",
      "personal": {
        "lastName": "Handey",
        "firstName": "Jack",
        "middleName": "Michael",
        "preferredFirstName": "Jackie",
        "phone": "+36 55 230 348",
        "mobilePhone": "+36 55 379 130",
        "dateOfBirth": "1995-10-10",
        "addresses": [
          {
            "countryId": "HU",
            "addressLine1": "Andr√°ssy Street 1.",
            "addressLine2": "",
            "city": "Budapest",
            "region": "Pest",
            "postalCode": "1061",
            "addressTypeId": "Home",
            "primaryAddress": true
          }
        ],
        "preferredContactTypeId": "mail"
      },
      "enrollmentDate": "2017-01-01",
      "expirationDate": "2019-01-01",
      "customFields": {
        "scope": "Design",
        "specialization": [
          "Business",
          "Jurisprudence"
        ]
      },
      "requestPreference": {
        "holdShelf": true,
        "delivery": true,
        "defaultServicePointId": "00000000-0000-1000-a000-000000000000",
        "defaultDeliveryAddressTypeId": "Home",
        "fulfillment": "Hold Shelf"
      },
      "departments": [
        "Accounting",
        "Finance",
        "Chemistry"
      ]
    }
  ],
  "included": {
    "departments": [
      {
        "name": "Accounting",
        "code": "ACC"
      },
      {
        "name": "Finance"
      }
    ]
  },
  "totalRecords": 1,
  "deactivateMissingUsers": true,
  "updateOnlyPresentFields": false,
  "sourceType": "test"
}

=== folio-org/mod-user-import/src/test/resources/user-import.json
{
    "users": [
        {
            "username": "usul",
            "externalSystemId": "10191",
            "patronGroup": "undergrad",
            "active": true,
            "personal": {
                "firstName": "Paul",
                "lastName": "Atreides",
                "middleName": "Mua'Dib",
                "preferredFirstName": "Usul"
            },
            "customFields": {
                "classYear": "2023"
            }
        },
        {
            "username": "chani",
            "externalSystemId": "10192",
            "patronGroup": "graduate",
            "active": true,
            "personal": {
                "pronouns": "He/Him",
                "firstName": "Chani",
                "lastName": "Kynes",
                "preferredFirstName": "Sihaya"
            },
            "customFields": {
                "classYear": "2024"
            }
        },
        {
            "username": "grouplessperson",
            "externalSystemId": "0"
        }
    ],
    "included": {
        "customFields": [
            {
                "refId": "classYear",
                "selectField": {
                    "options": {
                        "values": [
                            {
                                "value": "2023"
                            },
                            {
                                "value": "2024"
                            },
                            {
                                "value": "2025"
                            },
                            {
                                "value": "Employee"
                            },
                            {
                                "value": "Exchange Student"
                            },
                            {
                                "value": "Other"
                            },
                            {
                                "value": "Part Time"
                            }
                        ]
                    }
                }
            }
        ]
    },
    "totalRecords": 2,
    "deactivateMissingUsers": false,
    "updateOnlyPresentFields": true
}
